### ISSUE TITLE
Doesn't start properly on Firefox

### ISSUE THREAD

**Issue by matthewarcus** [FitzwilliamMuseum/fitz-kaleidoscope#27]
Firefox seems to get confused over loading the fragment shader (console log indicates it loads a dummy shader first and then the proper one, which doesn't seem to get initialized properly). It works for me if I change canvas.js to:

const sandbox = new GlslCanvas(canvas, { fragmentString: frag })

and deleting the line:

sandbox.load(frag)

(Original & fixed version work with Chrome - this is on Ubuntu 20.04)

**Comment by portableant** [comment]
@o-s-warren have you see n this comment from @matthewarcus (thank you!)

**Comment by o-s-warren** [comment]
Ah fantastic! Great fix, thank you @matthewarcus

**Comment by matthewarcus** [comment]
Glad to be of service...

Website looks good now on FF.

**Comment by portableant** [comment]
This also closes #15 Woohoo! Thanks @matthewarcus
